### ISSUE TITLE
add the app folder name 'AddressBookForJavaScript' as a public path?

### ISSUE THREAD

**Issue by mm108** [dreamfactorysoftware/javascript-sdk#5]
> Go to the Services tab in the admin console and click the 'files' service. Click the Config tab and add the app folder name 'AddressBookForJavaScript' as a public path. Now select the relevant container from the Container drop down. If you used the default storage settings to import the app then select "local" from the drop down list. Save your changes.

**add the app folder name 'AddressBookForJavaScript' as a public path**

What does the above exactly mean?

And in the DF console this is what I see when I click on the information button

![df_js_app](https://cloud.githubusercontent.com/assets/10776430/14086597/87d7a69c-f558-11e5-9fee-bf5684318d16.jpg)

**Comment by todda48** [comment]
In Values section enter AddressBookForJavaScript then click Save Service.

**Comment by mm108** [comment]
I did that and the result is "You do not have access to requested file."

When i run the app the url shows up as 
https://subd.mydomain.com/files/AddressBookForJavaScript/add_javascript/index.html

**Comment by mm108** [comment]
Btw should the "files" be there in the application URL? Thanks

**Comment by m-menon** [comment]
Btw should the "files" be there in the application URL? Thanks

**Comment by todda48** [comment]
Yes, mine is:

http://localhost:8888/files/AddressBookForJavaScript/add_javascript/index.html

And the app is working. Try reloading the admin app in your browser and go to Services-->Files-->Config. Maybe the path AddressBookForJavaScript didn't actually get saved.

**Comment by mm108** [comment]
cool...thanks. That got it working :+1:
