### ISSUE TITLE
Guest access for a API

### ISSUE THREAD

**Issue by mm108** [dreamfactorysoftware/javascript-sdk#6]
I have a requirement where the calling application cannot pass any credentials as such but just call an URL. So I have set restriction on the IP from where the application can reach my server but is it possible to have some kinda guest access where there is no need to pass credentials? It's just an API call to insert data into one of the collections. Thanks

**Comment by mm108** [comment]
Could this be the way? I save a key value using Look up keys and pass the key in ajax call or something?

> Lookup Keys Overview
> The DreamFactory administrator can create any number of "key value" pairs attached to a role. The key values are automatically substituted on the server. For example, key names can be used in the username and password fields required to hook up a SQL or NoSQL database. They can also be used in Email Templates or as parameters for external REST services. Any Lookup Key can be marked as private, and in this case the key value is securely encrypted on the server and is no longer accessible through the platform interface. Lookup keys for service configuration and credentials must be made private.

**Comment by drewpearce** [comment]
We have opted to reserve github issues for bugs/enhancements only. Not support. This use case is covered in the wiki. http://wiki.dreamfactory.com/DreamFactory/Tutorials/Setting_up_guest_access
